name: Fetch and Commit

on:
  workflow_dispatch:  # 允许手动触发工作流
  schedule:
    - cron: '0 9 * * *' # 每小时运行一次，调整为你的需要

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get install curl

      - name: Fetch website content
        id: fetch_content
        run: |
          # 获取前一天的日期，格式为 YYYYMMDD
          yesterday=$(date -d "yesterday" +%Y%m%d)
          content=$(curl -s "https://trends.google.com/trends/api/dailytrends?geo=US&hl=en&ed=${yesterday}&ns=15")
          filename="content_${yesterday}.txt"
          echo "${content}" > $filename
          echo "::set-output name=filename::$filename"  # 设置输出变量为文件名

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ steps.fetch_content.outputs.filename }}
          git commit -m "Update content from website for date ${yesterday}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/l499477004/trends.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 自动使用 GitHub 提供的 token
    
      - name: Clean up old files
        run: |
          find . -name 'content_*.txt' -type f -mtime +15 -exec rm {} \;
